services:
  workspace:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: workspace
    volumes:
      - ..:/workspace:cached
    # ports:
    #   - 80:8000
    command: sleep infinity
    extra_hosts:
      - "host.docker.internal:host-gateway"
